### ISSUE TITLE
Hives generating in the end

### ISSUE THREAD

**Issue by davqvist** [Lach01298/MoreBees#14]
Hey, thanks for the great mod. I noticed though that your hives generate in the end all over the place. I wonder if this is intentional or not, seems at least weird to me.

More Bees 1.1.5
Forge 12.18.2.2166

**Comment by Lach01298** [comment]
Strange bug it really shouldn't be happening because they are only allowed to spawn on stone must be a forestry bug or something im not noticing. anyway i added a biome check, did a bit of testing and now i can't find them in the end so fixed! even thought it shouldn't be happening in the first place.
