### ISSUE TITLE
conflict between More Bees and Forestry

### ISSUE THREAD

**Issue by 0Navis0** [Lach01298/MoreBees#45]
There is a conflict with More Bees 1.4.0 version and Forestry which causes Minecraft to crash while loading  https://pastebin.com/EECSmmPi

**Comment by Lach01298** [comment]
It not between more bees and forestry it because of a mod that adds nickel. Which mods add Nickel your using?

**Comment by 0Navis0** [comment]
Substratum, Embers, Tech Reborn, indirectly Tinker's Construct and Chisel.

**Comment by OrdinatorStouff** [comment]
I have been testing a new pack startup and encountered the same crash seen in the log posted above. I did some testing by removing/reducing mods to only MoreBees and mods that might add Nickel and none of them would cause a crash. Once Bookshelf API was added, however it started to crash again. I believe this issue is downstream of the [known issue](https://github.com/Darkhax-Minecraft/Bookshelf/issues/71) with Mekanism and BookshelfAPI.

**Comment by reddler97** [comment]
it is not caused by Mekanism + BookshelfAPI, i was testing it with mods that add nickel and have gotten the crash without either of the mods being installed, and even when i finally did install them without a mod that adds nickel it works fine. the issue you're referring to is un-related and apparently solved. Mekanism doesn't even add nickel by itself.

However Embers, and Substratum do add nickel and produce the crash. TechReborn also crashes but it only adds the Ingot and Dust(no Ore version).
i went on to test Tinkers' Construct, which adds just a nickel fluid(no survival way of getting nickel) but works fine. Chisel adds several decorative nickel blocks but again works fine. 
When testing IndustrialCraft2 it doesn't add nickel anywhere, but moreBee's drops there dusts' in favor for IC2's dust, so my best guess is that it is crashing because it is trying to create a recipe for nickel dust, but doesn't know how to/ is coded improperly

**Comment by jackytuutykcaj** [comment]
i have the same problem too
https://pastebin.com/msqtwJW1

**Comment by OrdinatorStouff** [comment]
@reddler97 I'd continued playing with it after my last comment and you're right; I was still seeing weird things and crashes. Thanks for continuing with some more thorough details.

**Comment by Dominance** [comment]
How would a mod adding nickel be the problem? Any mod should be able to extend the ore dictionary without causing issues with other mods. Unless said mod was doing something terribly wrong. anyhow https://paste.ubuntu.com/24802029/ Another one.

**Comment by drakray** [comment]
Another one https://pastebin.com/BguTEWHh

**Comment by Lach01298** [comment]
In reply to Dominance: you would think so and I've tried many times to fix my code but it doesn't seem to work every time it's mainly about when a mod ore dictionary's there ores i.e. init or post init.
And i know it's about nickel because that's the line it crashes on

**Comment by Lach01298** [comment]
new versions for 1.10 and 1.11 "should fix" if it does let me know if it doesn't also let me know

**Comment by reddler97** [comment]
i'm in 1.11 and, worked for me at least, which is good because i really wanted to play, and didn't want to load the world up and lose things from the conflicting mods

**Comment by jackytuutykcaj** [comment]
it works. thanks
